# Generated by Django 3.2 on 2021-04-26 21:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart_modified_at',
            field=models.DateTimeField(default=users.models.Profile.get_very_old_timestamp),
        ),
    ]
