# Generated by Django 3.1.5 on 2021-01-22 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
