# Generated by Django 3.1.5 on 2021-01-18 16:46

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_registrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stores.models.name_file),
        ),
    ]
